name: Frontend CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: List src files for debugging
        run: |
          ls -R src
          cat src/api.js
          cat src/__mocks__/api.js

      - name: Install dependencies
        run: npm install

      - name: Run Vitest
        run: NODE_ENV=test npx vitest run src/__tests__/Login.test.jsx
